using MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security;
using MensaGymnazium.IntranetGen3.Model;
using MensaGymnazium.IntranetGen3.Primitives;

namespace MensaGymnazium.IntranetGen3.DataLayer.Seeds.Subjects2026;

public class SubjectSeed : DataSeed<Subjects2026Profile>
{
	private readonly IUserRepository userRepository;

	public SubjectSeed(IUserRepository userRepository)
	{
		this.userRepository = userRepository;
	}

	public override void SeedData()
	{
		var users = userRepository.GetAll().Where(u => u.TeacherId is not null);

		var subjects = new List<Subject>
		{
			// Pondělí 16.3. – 08:30
			new() { SeedIdentifier = "MF26_111", Name = "Kyberbezpečnost", Description = @"TikTok, Instagram, Snapchat…
Každý like, story a „fun“ filtr může být další dílek skládačky, kterou ti někdo složí do dokonalého podvodu.

Řeč bude o tom, jak tě nejenom sociální sítě a lidé za obrazovkou okrádají o identitu – a jak se tomu bránit. Součástí bude diskuze/možnost ptát se na otázky z oblasti kyberbezpečnosti.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Březina")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_112", Name = "Fyzika", Description = @"Jan Rak je český jaderný a kvantový fyzik, který se zabývá výzkumem částicové fyziky a dlouhodobě pracoval na projektech v organizaci CERN ve Švýcarsku. Působil také jako profesor na univerzitě ve finském městě Jyväskylä. Vystupuje také na přednáškách a médiích, kde mluví o kvantové fyzice.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Rak")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_113", Name = "Dopravní podnik hl. m. Prahy", Description = @"Ing. Jiří Došlý. Několik let se věnoval problematice projektů spolupráce veřejného a soukromého sektoru (PPP projekty) v oblasti dopravní infrastruktury na Ministerstvu dopravy. Od roku 2010 působí v Dopravním podniku hl. m. Prahy, kde zodpovídá mimo jiné za zahraniční i tuzemské profesní vztahy.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Došlý")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Pondělí 16.3. – 10:15
			new() { SeedIdentifier = "MF26_121", Name = "Investigativní novinařina", Description = @"V žurnalistice působí již od 90. let, většinu své kariéry se věnoval tématům korupce, justiční mafie a organizovaného zločinu. Dlouhodobě se věnuje především rozkrývání ruského vlivu v České republice. Po odchodu z České televize roku 2024 založil investigativní web Odkryto.cz. Držitel ceny Novinářská křepelka (cena udělovaná mladým novinářům). Téma přednášky bude obecně z oboru investigativní novinařiny", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hynek")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_122", Name = "Finanční gramotnost", Description = @"hám digitálního světa. Dotkneme se také historie peněz, principů odpovědného úvěrování, nejčastějších triků online podvodníků a krátce i témat investic a kryptoměn — bez přehnaných očekávání, zato s důrazem na realitu. Cílem je poskytnout studentům praktické informace bez zbytečné teorie a ukázat, jak se vyhnout rizikům v online i offline světě.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Peták")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_123", Name = "Spisovatelství", Description = @"Autorka knih Prameny Vltavy, U severní zdi: Přišel čas platit účty za padesátá léta a Ignis fatuus, která je i v maturitní četbě. Její kniha prameny Vltavy se umístila na prvním místě mezi nominovanými publikacemi na cenu Johanna Steinbrennera v kategorii Beletrie/Poezie. Kniha Ignis fatuus byla v roce 2025 nominována mezi tři finalisty magnesia litera za fantastiku.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Klabouchová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Pondělí 16.3. – 12:20
			new() { SeedIdentifier = "MF26_131", Name = "Letečtí dispečeři", Description = @"Na této přednášce bude studentům představena funkce leteckého dispečera, následně si budou moci ve workshopové části vyzkoušet, jak takové plánování letu funguje, a to od přijetí nového letu až po jeho odlet.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Koláček")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_132", Name = "Sládek", Description = @"Přednášejícím bude sládek z pivovaru Staropramen. Je to 2. největší český pivovar, s tradicí přes 150 let sídlící v Praze. Vyváží pivo až do 30 cizích zemí. ", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Staropramen")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_133", Name = "Neurologie", Description = @"Na přednášce se podíváme, jak se z přírodních steroidů v hlavě stávají moderní léky na deprese, epilepsii, poruchy autistického spektra, nespavost nebo poranění mozku – a proč někdy tyto látky můžou mozek naopak rozhodit. Ukážeme si i roli vitaminu D jako mozkového steroidu a to, proč hormony během puberty, těhotenství nebo menopauzy tak dramaticky mění prožívání světa. Přijďte zjistit, jak malé molekuly, o kterých většinou vůbec nevíte, potichu rozhodují o tom, jak se cítíte, jak spíte, jak se soustředíte – a jak by z nich jednou mohly být chytré aktualizace pro mozek budoucnosti.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kudová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Úterý 17.3. – 08:30
			new() { SeedIdentifier = "MF26_211", Name = "Bitcoin a další kryptoměny - dávají pořád smysl?", Description = @"Ekonom, expert na kryptoměny, bývalý ředitel Liberálního institutu, bývalý politik a bývalý ředitel českého a slovenského Ludwig von Mises institutu", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Strouhal")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_212", Name = "Mikrobiom ve zdraví a nemoci", Description = @"Přednosta Ústavu klinické imunologie a alergologie 1. lékařské fakulty Univerzity Karlovy a Všeobecné fakultní nemocnice v Praze", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hrdý")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_213", Name = "Slibuje právo víc, než dokáže splnit?", Description = @"Přednáška se zaměří na tři konkrétní oblasti, kde se tento problém jasně ukazuje. Mzdová transparentnost a rovné odměňování: proč máme na trhu práce tolik různých nerovností v odměňování, i když zákon jasně říká, že za stejnou práci náleží stejný výdělek? Segregace Romů ve školství: evropské soudy ji opakovaně odsuzují, přesto se romské děti stále častěji ocitají ve speciálních školách a třídách. Kde selhávají právní nástroje? Manželství pro LGBT osoby: zatímco většina členských států EU tuto kapitolu již dávno uzavřela, Česko zůstává pozadu i přes výraznou podporu veřejnosti. Je to jen otázka času, nebo fundamentální spor o povahu manželství? ", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Tomšej")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Úterý 17.3. – 10:15
			new() { SeedIdentifier = "MF26_221", Name = "Ultrarychlostní běh", Description = @"Ultramaratonec a zakladatel běžecké školy. Propagátor a trenér běhu. Třikrát oběhl Českou republiku. Maraton nejrychleji zaběhl za 2:33:18", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Škorpil")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_222", Name = "Antropologie", Description = @"Martin Soukup je český kulturolog a kulturní antropolog. Od roku 2016 je zaměstnán na Fakultě sociálních věd Univerzity Karlovy. Je členem American Anthropological Association. Je laureátem Ceny Neuron pro mladé vědce 2017", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Soukup")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_223", Name = "Orientalismus", Description = @"Arabista, íranista, paštunista a islamolog, překladatel, tlumočník, diplomat a vysokoškolský pedagog. Honorární konzul Súdánu v ČR. Veterán z války v Perském zálivu (1990–1991). Během roku 2021 působil jako poradce předsedy vlády pro migraci. Téma přednášky zaměřené na islám.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Pelikán")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Úterý 17.3. – 12:20
			new() { SeedIdentifier = "MF26_231", Name = "Šachy", Description = @"David Navara je přední český šachový velmistr (titul od roku 2002) a mnohonásobný mistr České republiky. Dlouhodobě patří mezi světovou špičku, přičemž jeho nejvyšším umístěním v žebříčku FIDE bylo 13. místo v říjnu 2006. Je známý pro svůj vysoce kreativní herní styl.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Navara")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_232", Name = "Galeristika", Description = @"Nadia Rovderová je galeristka, kurátorka, fotografka, publicistka a také influercerka na sociálních sítích. Narodila se v Popradu a na Univerzitě Komenského v Bratislavě vystudovala žurnalistiku. Od začátku devadesátých let žije v Praze, kde v roce 2010 založila galerii Artinbox, která se stala nezávislým a otevřeným prostorem pro začínající i renomované české umělce, zahrnujícím celé spektrum výtvarných forem. Přednáška se bude hlavně zabývat galerií, jejím vznikem, managementem, ale záleží na zájmu přítomných :).", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Rovderová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_233", Name = "Erasmus a studium v zahraničí", Description = @"Odbornička na mezinárodní komunikaci a mezinárodní etiketu. Zabývá se např. specifiky různých kultur a jejich vlivy na profesní znalosti a komunikaci nebo kulturní aspekty při vyjednávání. Vystudovaná religionistka a ekonomka. Dlouhodobě žila v Izraeli. Na příští školní rok je s ní domlouván seminář o ekonomii a mezinárodní komunikaci na naší škole.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kahoferová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Středa 18.3. – 08:30
			new() { SeedIdentifier = "MF26_311", Name = "Jak nezisková organizace v oblasti zdravotnictví roste na více než 70 tisíc uživatelů", Description = @"Tech lead v německé bance Commerzbank. CTO aplikace Loono. Dobrovolník v Česk.digital. Před tím pracoval 9 let jako Tech lead v Air Bank.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Ladecký")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_312", Name = "Novinařina", Description = @"Celý dosavadní život se věnuje novinařině. I když žije a pracuje v Praze, za svůj domov považuje moravské Slovácko, kde má své kořeny. Ve volném čase se do tohoto kraje vrací a zachycuje vztah místních lidí k práci, krajině, lidovým tradicím a víře. Řadu let pracoval v MF DNES, kde psal převážně o politice. V posledních letech je zpravodajem a reportérem webu Aktuálně.cz se zaměřením na dění v nejvyšších patrech politiky. Hodně se ale pohybuje také v terénu, kde mapuje proměnlivé nálady i emoce voličů. Kromě psaní také fotí a natáčí videa. Publikuje rovněž vlastní video komentáře z „české politiky a novinařiny proti lži, nenávisti a blbé náladě“.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Bartoníček")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_313", Name = "Jak objevujeme planety mimo Sluneční soustavu?", Description = @"Popularizátor fyziky a astronomie, dramaturg popularizačního přednáškového cyklu Pátečníci, konající se každý pátek na Přírodovědecké fakultě UK v Praze.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Škorpík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Středa 18.3. – 10:15
			new() { SeedIdentifier = "MF26_321", Name = "Lékaři bez hranic", Description = @"Ředitelka české kanceláře Lékařů bez hranic. S organizací se zúčastnila misí v Kyrgyzstánu/Kazachstánu a keňském Nairobi. V letech 2014–2019 pracovala pro organizaci Člověk v tísni jako ředitelka Centra pro lidská práva a demokracii. Spolu se svými kolegy podporovala disidenty a lidskoprávní aktivisty působící v zemích s restriktivními režimy. Příležitostně jezdí do zahraničí s OBSE pozorovat volby jako mezinárodní pozorovatelka. ", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Horáková")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_322", Name = "Chronobiologie (denní rytmy, spánek, modré světlo...)", Description = @"Chronobiologie je vědní obor studující časovou organizaci biologických procesů a cyklické jevy (biorytmy) v organismech, odvozené od slunečních či měsíčních rytmů. Zkoumá vlivy na tělesné, duševní a emocionální funkce, zejména cirkadiánní rytmus (24hodinový cyklus). Klíčovou oblastí je regulace spánku a bdění hormonem melatoninem.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hübnerová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_323", Name = "Právo", Description = @"Právník, komercionalista a hlavní autor současného občanského zákoníku (89/2012 Sb.). Profesor v oboru obchodního práva. Člen vědecké rady Akademie věd ČR, Ústavu státu a práv AV ČR a právnických fakult v Praze a Olomouci. Člen legislativní rady vlády ČR. Na přelomu let 2011 a 2012 uveden do Právnické síně slávy. Pravidelně publikuje v odborných právnických časopisech.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Eliáš")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },

			// Středa 18.3. – 12:20
			new() { SeedIdentifier = "MF26_331", Name = "Od bodybuildera k náboženství", Description = @"Daniel Dvořák byl 2x mistr světa, 2x mistr Evropy, 11x mistr České republiky, mistr Anglie, Izraele a Rakouska, vítěz Evropské ligy v powerliftingu. V průběhu svého života se však dostal k náboženství a o svém příběhu vám popovídá v rámci přednášky. Zabývá se i zdravím, spánkem a dělá stále i osobního trenéra.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Dvořák")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_332", Name = "Youtubeřina, filmařina, fotografie a hudební tvorba", Description = @"Na internetu vystupuje také pod přezdívkou ERROR1K, pod kterou od roku 2017 publikuje videa na YouTube. Ve své tvorbě se věnuje především komentářům k různým tématům, reakcím, recenzím a obsahu zaměřenému na internetovou kulturu, intelekt a audiovizuální tvorbu. Sám si potrpí na dobrý audiovizuální dojem a svou produkci si vytváří sám, od scénáře přes natáčení až po střih. Studoval filmovou střední školu, je fotografem a filmařem na volné noze a v posledních pár letech se začal věnovat hudební, převážně rapové tvorbě.", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Šafařík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar },
			new() { SeedIdentifier = "MF26_333", Name = "Beseda s bývalým předsedou vlády", Description = @"Politolog, vysokoškolský učitel a politik (mj. bývalý předseda vlády a bývalý předseda ODS). První profesor v oboru politologie v ČR, v minulosti dlouhodobý vedoucí katedry politologie Masarykovy univerzity. Rektor Masarykovy univerzity (2004 – 2011), předseda České konference rektorů (2009 – 2011). Člen Rady Ústavu pro studium totalitních režimů (2007 -2012). V letech 2012 – 2013 ministr školství, mládeže a tělovýchovy, předtím od roku 2011 hlavní vědecký pracovník předsedy vlády Petra Nečase. Od roku 2013 poslanec PSP ČR za Jihomoravský kraj, současně člen výboru pro vědu, vzdělávání, mládež a sport; v letech 2017 – 2021 též místopředseda PSP ČR. Historicky nejdéle sloužící předseda Občanské demokratické strany (18. 1. 2014 – 17. 1. 2026). Od 28. 11. 2021 do 15. 12. 2025 předseda vlády České republiky", Capacity = 40, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Fiala")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar }
		};

		Seed(For(subjects.ToArray()).PairBy(subject => subject.SeedIdentifier)
			.AfterSave(item => item.SeedEntity.TeacherRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.TypeRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.GradeRelations.ForEach(gr => gr.SubjectId = item.PersistedEntity.Id))
			.AndForAll(subject => subject.TeacherRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.TeacherId))
			.AndForAll(subject => subject.TypeRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.SubjectTypeId))
			.AndForAll(subject => subject.GradeRelations, configuration => configuration.PairBy(gr => gr.SubjectId, gr => gr.GradeId))
		);
	}
}
