using MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security;
using MensaGymnazium.IntranetGen3.DataLayer.Seeds.Demo;
using MensaGymnazium.IntranetGen3.Model;
using MensaGymnazium.IntranetGen3.Primitives;

namespace MensaGymnazium.IntranetGen3.DataLayer.Seeds.Subjects2026;

public class SubjectSeed : DataSeed<Subjects2026Profile>
{
	private readonly IUserRepository userRepository;

	public SubjectSeed(IUserRepository userRepository)
	{
		this.userRepository = userRepository;
	}

	public override void SeedData()
	{
		var users = userRepository.GetAll().Where(u => u.TeacherId is not null);

		var subjects = new List<Subject>();

		// Pondělí 16.3. – 08:30
		subjects.Add(new Subject() { SeedIdentifier = "MF26_111", Name = "Kyberbezpečnostní specialista", Description = "Kyberbezpečnostní specialista", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Březina")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_112", Name = "Fyzik", Description = "Fyzik", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Rak")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_113", Name = "Ředitel pro korporátní záležitosti DPP", Description = "Ředitel pro korporátní záležitosti DPP", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Došlý")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Pondělí 16.3. – 10:15
		subjects.Add(new Subject() { SeedIdentifier = "MF26_121", Name = "Investigativní novinář", Description = "Investigativní novinář", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hynek")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_122", Name = "Local risk and compliance manager", Description = "Local risk and compliance manager", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Peták")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_123", Name = "Spisovatelka a novinářka", Description = "Spisovatelka a novinářka", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Klabouchová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Pondělí 16.3. – 12:20
		subjects.Add(new Subject() { SeedIdentifier = "MF26_131", Name = "Letečtí dispečeři", Description = "Letečtí dispečeři", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Koláček")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_132", Name = "Sládek", Description = "Sládek", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Staropramen")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_133", Name = "Neuroložka", Description = "Neuroložka", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kudová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Úterý 17.3. – 08:30
		subjects.Add(new Subject() { SeedIdentifier = "MF26_211", Name = "Ekonom", Description = "Ekonom", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Strouhal")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_212", Name = "Přednosta na 1. lékařské fakultě UK", Description = "Přednosta na 1. lékařské fakultě UK", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hrdý")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_213", Name = "Právník", Description = "Právník", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Tomšej")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Úterý 17.3. – 10:15
		subjects.Add(new Subject() { SeedIdentifier = "MF26_221", Name = "Ultrarychlostní běžec", Description = "Ultrarychlostní běžec", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Škorpil")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_222", Name = "Antropolog", Description = "Antropolog", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Soukup")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_223", Name = "Orientalista", Description = "Orientalista", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Pelikán")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Úterý 17.3. – 12:20
		subjects.Add(new Subject() { SeedIdentifier = "MF26_231", Name = "Šachový velmistr", Description = "Šachový velmistr", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Navara")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_232", Name = "Galeristka a výtvarnice", Description = "Galeristka a výtvarnice", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Rovderová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_233", Name = "Mezinárodní komunikace", Description = "Mezinárodní komunikace", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kahoferová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Středa 18.3. – 08:30
		subjects.Add(new Subject() { SeedIdentifier = "MF26_311", Name = "Tech lead IT", Description = "Tech lead IT", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Ladecký")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_312", Name = "Novinář", Description = "Novinář", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Bartoníček")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_313", Name = "Fyzik a astronom", Description = "Fyzik a astronom", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Škorpík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Středa 18.3. – 10:15
		subjects.Add(new Subject() { SeedIdentifier = "MF26_321", Name = "Ředitelka Lékařů bez hranic", Description = "Ředitelka Lékařů bez hranic", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Horáková")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_322", Name = "Chronobioložka", Description = "Chronobioložka", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Hübnerová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_323", Name = "Právník", Description = "Právník", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Eliáš")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		// Středa 18.3. – 12:20
		subjects.Add(new Subject() { SeedIdentifier = "MF26_331", Name = "Bodybuilder a kněz", Description = "Bodybuilder a kněz", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Dvořák")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_332", Name = "Youtuber, filmař, fotogramn a hudební tvůrce", Description = "Youtuber, filmař, fotogramn a hudební tvůrce", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Šafařík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF26_333", Name = "Politik a politolog", Description = "Politik a politolog", Capacity = 45, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Fiala")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Prima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		Seed(For(subjects.ToArray()).PairBy(subject => subject.SeedIdentifier)
			.AfterSave(item => item.SeedEntity.TeacherRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.TypeRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.GradeRelations.ForEach(gr => gr.SubjectId = item.PersistedEntity.Id))
			.AndForAll(subject => subject.TeacherRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.TeacherId))
			.AndForAll(subject => subject.TypeRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.SubjectTypeId))
			.AndForAll(subject => subject.GradeRelations, configuration => configuration.PairBy(gr => gr.SubjectId, gr => gr.GradeId))
		);
	}
}
