//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaGymnazium.IntranetGen3.Contracts.ModelMetadata;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class SigningRuleMetadata
{
	public const int DescriptionMaxLength = Int32.MaxValue;
	public const int NameMaxLength = 100;
	public const int SeedItemIdentifierMaxLength = 50;
}
