<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BlazorApplicationInsights" Version="3.3.0" />
    <PackageVersion Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageVersion Include="FluentValidation" Version="11.11.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageVersion Include="Havit.Blazor.Components.Web.Bootstrap" Version="4.24.2" />
    <PackageVersion Include="Havit.Blazor.Grpc.Client.WebAssembly" Version="1.8.4" />
    <PackageVersion Include="Havit.Blazor.Grpc.Core" Version="1.8.4" />
    <PackageVersion Include="Havit.Blazor.Grpc.Server" Version="1.8.4" />
    <PackageVersion Include="Havit.Core" Version="2.0.36" />
    <PackageVersion Include="Havit.Data.EntityFrameworkCore" Version="2.10.2" />
    <PackageVersion Include="Havit.Data.EntityFrameworkCore.Abstractions" Version="2.10.0" />
    <PackageVersion Include="Havit.Data.EntityFrameworkCore.CodeGenerator" Version="2.10.2" />
    <PackageVersion Include="Havit.Data.EntityFrameworkCore.Patterns" Version="2.10.2" />
    <PackageVersion Include="Havit.Data.Patterns" Version="2.1.33" />
    <PackageVersion Include="Havit.Extensions.DependencyInjection" Version="2.0.14" />
    <PackageVersion Include="Havit.Extensions.DependencyInjection.Abstractions" Version="2.0.22" />
    <PackageVersion Include="Havit.Extensions.Localization" Version="1.0.2" />
    <PackageVersion Include="Havit.Model" Version="2.0.5" />
    <PackageVersion Include="Havit.Services" Version="2.0.51" />
    <PackageVersion Include="Havit.Services.Azure" Version="2.0.51" />
    <PackageVersion Include="Havit.SourceGenerators.StrongApiStringLocalizers" Version="3.0.0" />
    <PackageVersion Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="4.9.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.7.0" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.7.0" />
    <PackageVersion Include="protobuf-net" Version="3.2.56" />
    <PackageVersion Include="protobuf-net.Grpc" Version="1.2.5" />
    <PackageVersion Include="Scrutor" Version="6.0.1" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
  </ItemGroup>

  <ItemGroup Condition="'$(ProjectName.EndsWith(`Tests`))' == 'False'">
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
  </ItemGroup>

</Project>
