//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class ApplicationSettingsEntries : Havit.Data.Patterns.DataEntries.DataEntries<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings>, IApplicationSettingsEntries 
{
	private MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings current;

	public MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings Current => current ??= GetEntry(MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings.Entry.Current);

	public ApplicationSettingsEntries(MensaGymnazium.IntranetGen3.DataLayer.Repositories.Common.IApplicationSettingsRepository repository)
		: base(repository)
	{
	}
}
