//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DependencyInjection;
using Havit.Data.EntityFrameworkCore.Patterns.Infrastructure;
using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.DataSources;
using Havit.Data.Patterns.Infrastructure;
using Havit.Data.Patterns.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace MensaGymnazium.IntranetGen3.DataLayer;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static partial class DataLayerServiceExtensions
{
	public static IServiceCollection AddDataLayerServices(this IServiceCollection services, ComponentRegistrationOptions options = null)
	{
		services.AddDataLayerCoreServices(options);
	
		AddDataSources(services);
		AddRepositories(services);
		AddDataEntries(services);
		AddEntityKeyAccessors(services);

		return services;
	}

	private static void AddDataSources(IServiceCollection services)
	{
		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.Common.IApplicationSettingsDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Common.ApplicationSettingsDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Common.ApplicationSettingsDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.IEducationalAreaDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.EducationalAreaDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.EducationalArea>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.EducationalAreaDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.IGradeDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GradeDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Grade>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GradeDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.IGradeRegistrationCriteriaDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GradeRegistrationCriteriaDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GradeRegistrationCriteriaDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.IGraduationSubjectDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GraduationSubjectDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.GraduationSubject>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.GraduationSubjectDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.IStudentDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.StudentDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Security.Student>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.StudentDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.ITeacherDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.TeacherDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Security.Teacher>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.TeacherDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.IUserDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.UserDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Security.User>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.UserDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.IStudentSubjectRegistrationDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.StudentSubjectRegistrationDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.StudentSubjectRegistrationDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.ISubjectDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.SubjectDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.Subject>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.SubjectDbDataSource>();

		services.TryAddTransient<MensaGymnazium.IntranetGen3.DataLayer.DataSources.ISubjectCategoryDataSource, MensaGymnazium.IntranetGen3.DataLayer.DataSources.SubjectCategoryDbDataSource>();
		services.TryAddTransient<IDataSource<MensaGymnazium.IntranetGen3.Model.SubjectCategory>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.SubjectCategoryDbDataSource>();

	}

	private static void AddRepositories(IServiceCollection services)
	{
		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Common.IApplicationSettingsRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Common.ApplicationSettingsDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Common.IApplicationSettingsRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Common.ApplicationSettingsDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IEducationalAreaRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.EducationalAreaDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.EducationalArea, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IEducationalAreaRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.EducationalArea, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.EducationalAreaDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGradeRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GradeDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Grade, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGradeRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Grade, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GradeDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGradeRegistrationCriteriaRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GradeRegistrationCriteriaDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGradeRegistrationCriteriaRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GradeRegistrationCriteriaDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGraduationSubjectRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GraduationSubjectDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.GraduationSubject, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IGraduationSubjectRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.GraduationSubject, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.GraduationSubjectDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.IStudentRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.StudentDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Security.Student, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.IStudentRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Security.Student, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.StudentDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.ITeacherRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.TeacherDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Security.Teacher, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.ITeacherRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Security.Teacher, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.TeacherDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.IUserRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.UserDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Security.User, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.IUserRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Security.User, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security.UserDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IStudentSubjectRegistrationRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.StudentSubjectRegistrationDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.IStudentSubjectRegistrationRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.StudentSubjectRegistrationDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.SubjectDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.Subject, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Subject, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.SubjectDbRepositoryQueryProvider>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectCategoryRepository, MensaGymnazium.IntranetGen3.DataLayer.Repositories.SubjectCategoryDbRepository>();
		services.TryAddScoped<IRepository<MensaGymnazium.IntranetGen3.Model.SubjectCategory, System.Int32>>(sp => sp.GetRequiredService<MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectCategoryRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.SubjectCategory, System.Int32>, MensaGymnazium.IntranetGen3.DataLayer.Repositories.SubjectCategoryDbRepositoryQueryProvider>();

	}

	private static void AddDataEntries(IServiceCollection services)
	{
		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.DataEntries.Common.IApplicationSettingsEntries, MensaGymnazium.IntranetGen3.DataLayer.DataEntries.Common.ApplicationSettingsEntries>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.DataEntries.IEducationalAreaEntries, MensaGymnazium.IntranetGen3.DataLayer.DataEntries.EducationalAreaEntries>();

		services.TryAddScoped<MensaGymnazium.IntranetGen3.DataLayer.DataEntries.IGraduationSubjectEntries, MensaGymnazium.IntranetGen3.DataLayer.DataEntries.GraduationSubjectEntries>();

	}

	private static void AddEntityKeyAccessors(IServiceCollection services)
	{
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Common.ApplicationSettings, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.EducationalArea, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.EducationalArea, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Grade, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Grade, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.GraduationSubject, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.GraduationSubject, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.Student, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.Student, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.Teacher, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.Teacher, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.User, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Security.User, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Subject, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.Subject, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.SubjectCategory, System.Int32>, DbEntityKeyAccessor<MensaGymnazium.IntranetGen3.Model.SubjectCategory, System.Int32>>();
	}
}
