//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataSources.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeSigningRuleDataSource : FakeDataSource<MensaGymnazium.IntranetGen3.Model.SigningRule>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.ISigningRuleDataSource
	{
		public FakeSigningRuleDataSource(params MensaGymnazium.IntranetGen3.Model.SigningRule[] data)
			: this((IEnumerable<MensaGymnazium.IntranetGen3.Model.SigningRule>)data)
		{			
		}

		public FakeSigningRuleDataSource(IEnumerable<MensaGymnazium.IntranetGen3.Model.SigningRule> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}