//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeGradeRegistrationCriteriaDataSource : FakeDataSource<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.IGradeRegistrationCriteriaDataSource
{
	public FakeGradeRegistrationCriteriaDataSource(params MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria[] data)
		: this((IEnumerable<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria>)data)
	{			
	}

	public FakeGradeRegistrationCriteriaDataSource(IEnumerable<MensaGymnazium.IntranetGen3.Model.GradeRegistrationCriteria> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
