//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeStudentSubjectRegistrationDataSource : FakeDataSource<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.IStudentSubjectRegistrationDataSource
{
	public FakeStudentSubjectRegistrationDataSource(params MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration[] data)
		: this((IEnumerable<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration>)data)
	{			
	}

	public FakeStudentSubjectRegistrationDataSource(IEnumerable<MensaGymnazium.IntranetGen3.Model.StudentSubjectRegistration> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
