//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface IEducationalAreaEntries : Havit.Data.Patterns.DataEntries.IDataEntries
{
	MensaGymnazium.IntranetGen3.Model.EducationalArea ArtCulture { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea HumanHealth { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea HumanNature { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea HumanSociety { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea HumanWork { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea Informatics { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea LanguageCommunication { get; }
	MensaGymnazium.IntranetGen3.Model.EducationalArea MathApplication { get; }
}
