//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Patterns.DataEntries;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public interface IGradeEntries : IDataEntries
	{
		MensaGymnazium.IntranetGen3.Model.Grade Kvarta { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Kvinta { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Oktava { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Prima { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Sekunda { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Septima { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Sexta { get; }
			
		MensaGymnazium.IntranetGen3.Model.Grade Tercie { get; }
			
	}
}