//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface IGraduationSubjectEntries : Havit.Data.Patterns.DataEntries.IDataEntries
{
	MensaGymnazium.IntranetGen3.Model.GraduationSubject ArtHistory { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Biology { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Chemistry { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject CzechLanguageLiterature { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Economy { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject English { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject ForeignLanguage { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Geography { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject History { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject HumanWork { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Informatics { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Law { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Math { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Philosophy { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Physics { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject PoliticalScience { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Psychology { get; }
	MensaGymnazium.IntranetGen3.Model.GraduationSubject Sociology { get; }
}
