//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Patterns.DataEntries;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public interface ISubjectTypeEntries : IDataEntries
	{
		MensaGymnazium.IntranetGen3.Model.SubjectType ArtCulture { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType HumanHealth { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType HumanNature { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType HumanSociety { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType HumanWork { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType Informatics { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType LanguageCommunication { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectType MathApplication { get; }
			
	}
}