//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Patterns.DataEntries;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public interface ISubjectCategoryEntries : IDataEntries
	{
		MensaGymnazium.IntranetGen3.Model.SubjectCategory ExtensionSeminar { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectCategory ForeignLanguage { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectCategory GraduationSeminar { get; }
			
		MensaGymnazium.IntranetGen3.Model.SubjectCategory SpecialisationSeminar { get; }
			
	}
}