//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class SubjectTypeEntries : DataEntries<MensaGymnazium.IntranetGen3.Model.SubjectType>, ISubjectTypeEntries 
	{
		public MensaGymnazium.IntranetGen3.Model.SubjectType ArtCulture
        {
            get
            {
				if (artCulture == null)
				{
					artCulture = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.ArtCulture);
				}
				return artCulture;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType artCulture;

		public MensaGymnazium.IntranetGen3.Model.SubjectType HumanHealth
        {
            get
            {
				if (humanHealth == null)
				{
					humanHealth = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.HumanHealth);
				}
				return humanHealth;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType humanHealth;

		public MensaGymnazium.IntranetGen3.Model.SubjectType HumanNature
        {
            get
            {
				if (humanNature == null)
				{
					humanNature = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.HumanNature);
				}
				return humanNature;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType humanNature;

		public MensaGymnazium.IntranetGen3.Model.SubjectType HumanSociety
        {
            get
            {
				if (humanSociety == null)
				{
					humanSociety = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.HumanSociety);
				}
				return humanSociety;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType humanSociety;

		public MensaGymnazium.IntranetGen3.Model.SubjectType HumanWork
        {
            get
            {
				if (humanWork == null)
				{
					humanWork = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.HumanWork);
				}
				return humanWork;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType humanWork;

		public MensaGymnazium.IntranetGen3.Model.SubjectType Informatics
        {
            get
            {
				if (informatics == null)
				{
					informatics = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.Informatics);
				}
				return informatics;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType informatics;

		public MensaGymnazium.IntranetGen3.Model.SubjectType LanguageCommunication
        {
            get
            {
				if (languageCommunication == null)
				{
					languageCommunication = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.LanguageCommunication);
				}
				return languageCommunication;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType languageCommunication;

		public MensaGymnazium.IntranetGen3.Model.SubjectType MathApplication
        {
            get
            {
				if (mathApplication == null)
				{
					mathApplication = GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectType.Entry.MathApplication);
				}
				return mathApplication;
            }
        }
		private MensaGymnazium.IntranetGen3.Model.SubjectType mathApplication;

		public SubjectTypeEntries(MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectTypeRepository repository)
			: base(repository)
		{
		}
	}
}