//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaGymnazium.IntranetGen3.DataLayer.DataEntries;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class SubjectCategoryEntries : Havit.Data.Patterns.DataEntries.DataEntries<MensaGymnazium.IntranetGen3.Model.SubjectCategory>, ISubjectCategoryEntries 
{
	private MensaGymnazium.IntranetGen3.Model.SubjectCategory extensionSeminar;
	private MensaGymnazium.IntranetGen3.Model.SubjectCategory foreignLanguage;
	private MensaGymnazium.IntranetGen3.Model.SubjectCategory graduationSeminar;
	private MensaGymnazium.IntranetGen3.Model.SubjectCategory specialisationSeminar;

	public MensaGymnazium.IntranetGen3.Model.SubjectCategory ExtensionSeminar => extensionSeminar ??= GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectCategory.Entry.ExtensionSeminar);
	public MensaGymnazium.IntranetGen3.Model.SubjectCategory ForeignLanguage => foreignLanguage ??= GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectCategory.Entry.ForeignLanguage);
	public MensaGymnazium.IntranetGen3.Model.SubjectCategory GraduationSeminar => graduationSeminar ??= GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectCategory.Entry.GraduationSeminar);
	public MensaGymnazium.IntranetGen3.Model.SubjectCategory SpecialisationSeminar => specialisationSeminar ??= GetEntry(MensaGymnazium.IntranetGen3.Model.SubjectCategory.Entry.SpecialisationSeminar);

	public SubjectCategoryEntries(MensaGymnazium.IntranetGen3.DataLayer.Repositories.ISubjectCategoryRepository repository)
		: base(repository)
	{
	}
}
