//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeRoleDataSource : FakeDataSource<MensaGymnazium.IntranetGen3.Model.Security.Role>, MensaGymnazium.IntranetGen3.DataLayer.DataSources.Security.IRoleDataSource
	{
		public FakeRoleDataSource(params MensaGymnazium.IntranetGen3.Model.Security.Role[] data)
			: this((IEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Role>)data)
		{			
		}

		public FakeRoleDataSource(IEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Role> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}