//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Microsoft.EntityFrameworkCore;
using DbContext = Havit.Data.EntityFrameworkCore.DbContext;

namespace MensaGymnazium.IntranetGen3.DataLayer.Repositories;

internal class SubjectDbRepositoryQueryProvider : IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Subject, System.Int32>
{
	private readonly Func<DbContext, System.Int32, MensaGymnazium.IntranetGen3.Model.Subject> _getObjectQuery;
	private readonly Func<DbContext, System.Int32, CancellationToken, Task<MensaGymnazium.IntranetGen3.Model.Subject>> _getObjectAsyncQuery;
	private readonly Func<DbContext, System.Int32[], IEnumerable<MensaGymnazium.IntranetGen3.Model.Subject>> _getObjectsQuery;
	private readonly Func<DbContext, System.Int32[], IAsyncEnumerable<MensaGymnazium.IntranetGen3.Model.Subject>> _getObjectsAsyncQuery;

	public SubjectDbRepositoryQueryProvider()
	{
		_getObjectQuery = EF.CompileQuery((DbContext dbContext, System.Int32 id) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Subject>()
			.TagWith("SubjectDbRepository.GetObject")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32 id, CancellationToken cancellationToken) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Subject>()
			.TagWith("SubjectDbRepository.GetObjectAsync")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectsQuery = EF.CompileQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Subject>()
			.TagWith("SubjectDbRepository.GetObjects")
			.Where(entity => ids.Contains(entity.Id)));

		_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Subject>()
			.TagWith("SubjectDbRepository.GetObjectsAsync")
			.Where(entity => ids.Contains(entity.Id)));
	}

	public Func<DbContext, System.Int32, MensaGymnazium.IntranetGen3.Model.Subject> GetGetObjectQuery() => _getObjectQuery;
	public Func<DbContext, System.Int32, CancellationToken, Task<MensaGymnazium.IntranetGen3.Model.Subject>> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;
	public Func<DbContext, System.Int32[], IEnumerable<MensaGymnazium.IntranetGen3.Model.Subject>> GetGetObjectsQuery() => _getObjectsQuery;
	public Func<DbContext, System.Int32[], IAsyncEnumerable<MensaGymnazium.IntranetGen3.Model.Subject>> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;
}
