//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Microsoft.EntityFrameworkCore;
using DbContext = Havit.Data.EntityFrameworkCore.DbContext;

namespace MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security;

internal class TeacherDbRepositoryQueryProvider : IRepositoryQueryProvider<MensaGymnazium.IntranetGen3.Model.Security.Teacher, System.Int32>
{
	private readonly Func<DbContext, System.Int32, MensaGymnazium.IntranetGen3.Model.Security.Teacher> _getObjectQuery;
	private readonly Func<DbContext, System.Int32, CancellationToken, Task<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> _getObjectAsyncQuery;
	private readonly Func<DbContext, System.Int32[], IEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> _getObjectsQuery;
	private readonly Func<DbContext, System.Int32[], IAsyncEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> _getObjectsAsyncQuery;

	public TeacherDbRepositoryQueryProvider()
	{
		_getObjectQuery = EF.CompileQuery((DbContext dbContext, System.Int32 id) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Security.Teacher>()
			.TagWith("TeacherDbRepository.GetObject")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32 id, CancellationToken cancellationToken) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Security.Teacher>()
			.TagWith("TeacherDbRepository.GetObjectAsync")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectsQuery = EF.CompileQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Security.Teacher>()
			.TagWith("TeacherDbRepository.GetObjects")
			.Where(entity => ids.Contains(entity.Id)));

		_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<MensaGymnazium.IntranetGen3.Model.Security.Teacher>()
			.TagWith("TeacherDbRepository.GetObjectsAsync")
			.Where(entity => ids.Contains(entity.Id)));
	}

	public Func<DbContext, System.Int32, MensaGymnazium.IntranetGen3.Model.Security.Teacher> GetGetObjectQuery() => _getObjectQuery;
	public Func<DbContext, System.Int32, CancellationToken, Task<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;
	public Func<DbContext, System.Int32[], IEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> GetGetObjectsQuery() => _getObjectsQuery;
	public Func<DbContext, System.Int32[], IAsyncEnumerable<MensaGymnazium.IntranetGen3.Model.Security.Teacher>> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;
}
