using MensaGymnazium.IntranetGen3.DataLayer.Repositories.Security;
using MensaGymnazium.IntranetGen3.DataLayer.Seeds.Demo;
using MensaGymnazium.IntranetGen3.Model;
using MensaGymnazium.IntranetGen3.Primitives;

namespace MensaGymnazium.IntranetGen3.DataLayer.Seeds.Subjects2022;

public class SubjectSeed : DataSeed<Subjects2022Profile>
{
	private readonly IUserRepository userRepository;

	public SubjectSeed(IUserRepository userRepository)
	{
		this.userRepository = userRepository;
	}

	public override void SeedData()
	{
		var users = userRepository.GetAll().Where(u => u.TeacherId is not null);

		var subjects = new List<Subject>();

		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-1-1", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-1-2", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-1-3", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-2-1", Name = "Praxe v České televizi", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Železný")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-2-2", Name = "Slepá místa kriminalistiky – o chybách forenzní vědy a kauzách, kde sehrály velkou roli", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Šimková")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-2-3", Name = "Vrchní státní zastupitelství", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Bradáčová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-3-1", Name = "Debata o závodech formule, o sběratelství starých a vzácných aut, o investicích", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Turek")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-3-2", Name = "Ilustrátorství", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Strejček")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_1-3-3", Name = "Lucidní snění", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Monday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Skryja")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-1-1", Name = "Vězeňská psychologie", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Jiřička")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-1-2", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-1-3", Name = "Řízení letového provozu", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Pražan")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-2-1", Name = "Psychedeliky asistovaná psychoterapie, úskalí užívání psychedelik", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Adámková")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-2-2", Name = "Hypnotizér", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kroulík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-2-3", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-3-1", Name = "Aplikace Záchranka (aplikace zachraňující životy)", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Maleňák")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-3-2", Name = "Role náboženství v moderní společnosti, fenomén nových náboženských hnutí", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Václavík")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_2-3-3", Name = "Wim Hofova metoda dýchání, otužování", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Tuesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Chomát")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-1-1", Name = "Jak se zkouší letadla", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Vlk")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-1-2", Name = "Herectví, moderátorství", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Sokol")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-1-3", Name = "Módní návrhářství", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Vytlačilová")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-2-1", Name = "Freeride, BASE jumping, horolezectví", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Kaleta")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-2-2", Name = "Žurnalistika", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Šídlo")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-2-3", Name = "Generální štáb armády ČR", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Šedivý")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-3-1", Name = "Placeholder", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)1, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Placeholder")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-3-2", Name = "Herectví", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)2, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Pavlásek")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });
		subjects.Add(new Subject() { SeedIdentifier = "MF22_3-3-3", Name = "Přežití ve městě", Description = "Placeholder", Capacity = 37, ScheduleDayOfWeek = DayOfWeek.Wednesday, ScheduleSlotInDay = (ScheduleSlotInDay)3, TeacherRelations = { new SubjectTeacherRelation() { TeacherId = users.First(t => t.Name.Contains("Ibrahim")).TeacherId.Value } }, TypeRelations = { new SubjectTypeRelation() { SubjectTypeId = (int)SubjectType.Entry.Informatics } }, GradeRelations = { new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sekunda }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Tercie }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvarta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Kvinta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Sexta }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Septima }, new SubjectGradeRelation() { GradeId = (int)GradeEntry.Oktava }, }, CategoryId = (int)SubjectCategory.Entry.GraduationSeminar });

		Seed(For(subjects.ToArray()).PairBy(subject => subject.SeedIdentifier)
			.AfterSave(item => item.SeedEntity.TeacherRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.TypeRelations.ForEach(tr => tr.SubjectId = item.PersistedEntity.Id))
			.AfterSave(item => item.SeedEntity.GradeRelations.ForEach(gr => gr.SubjectId = item.PersistedEntity.Id))
			.AndForAll(subject => subject.TeacherRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.TeacherId))
			.AndForAll(subject => subject.TypeRelations, configuration => configuration.PairBy(tr => tr.SubjectId, tr => tr.SubjectTypeId))
			.AndForAll(subject => subject.GradeRelations, configuration => configuration.PairBy(gr => gr.SubjectId, gr => gr.GradeId))
		);
	}
}
